config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'contacts#index'
  get 'contacts/new', as: 'new_contact'
  get 'contacts/index', as: 'contacts'
  post '/contacts/create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :group
  paginates_per 10
	
 
  def gravatar
	hash = Digest::MD5.hexdigest(email.downcase)
	"https://www.gravatar.com/avatar/#{hash}"
  end

end

app/models/group.rb
class Group < ApplicationRecord
	has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def index
		if params[:group_id] && !params[:group_id].empty?
			@contacts = Group.find(params[:group_id]).contacts.page(params[:page])
		else
			@contacts = Contact.page(params[:page])
		end
	end
	
	def new
		
	end

	def create
		@contact = Contact.new(contact_params)
		if @contact.save
			flash[:success] = "Contact was successfully created."
			redirect_to contacts_path
		else
			render 'new'
		end
	end

	private

	def contact_params
		params.require(:contact).permit(:name, :email, :company, :address, :phone, :group_id)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_contact.html.erb
	       <tr>
                 <td class="middle">
                     <div class="media">
                       <div class="media-left">
                         <a href="#">
			   <%= image_tag contact.gravatar, class: "media-object"  %>
                        </a>
                      </div>
                      <div class="media-body">
                        <h4 class="media-heading"><%= contact.name %></h4>
                        <address>
                          <strong><%= contact.company %></strong><br>
                          <%= contact.email %>
                        </address>
                      </div>
                    </div>
                  </td>
                  <td width="100" class="middle">
                    <div>
                      <a href="#" class="btn btn-circle btn-default btn-xs" title="Edit">
                        <i class="glyphicon glyphicon-edit"></i>
                      </a>
                      <a href="#" class="btn btn-circle btn-danger btn-xs" title="Edit">
                       <i class="glyphicon glyphicon-remove"></i>
                      </a>
                    </div>
                  </td>
                </tr>

app/views/contacts/index.html.erb
<% if @contacts.blank? %>
  <div class="alert alert-warning">
	  <strong>Record not found!</strong>
  </div>          
<% end %>


	  <div class="panel panel-default">
            <table class="table">
		<%= render @contacts %>
            </table>            
          </div>

          <div class="text-center">
		<%= paginate @contacts %>			
          </div>
      

app/views/contacts/new.html.erb
<div class="panel panel-default">
            <div class="panel-heading">
              <strong>Add Contact</strong>
            </div>           
	
	    <form action="/contacts/create" method="post" >
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"
            <div class="panel-body">
              <div class="form-horizontal">
                <div class="row">
                  <div class="col-md-8">
                    <div class="form-group">
                      <label for="name" class="control-label col-md-3">Name</label>
                      <div class="col-md-8">
                        <input type="text" name="contact[name]" id="name" class="form-control">
                      </div>
                    </div>

                    <div class="form-group">
                      <label for="company" class="control-label col-md-3">Company</label>
                      <div class="col-md-8">
                        <input type="text" name="contact[company]" id="company" class="form-control">
                      </div>
                    </div>

                    <div class="form-group">
                      <label for="email" class="control-label col-md-3">Email</label>
                      <div class="col-md-8">
                        <input type="text" name="contact[email]" id="email" class="form-control">
                      </div>
                    </div>

                    <div class="form-group">
                      <label for="phone" class="control-label col-md-3">Phone</label>
                      <div class="col-md-8">
                        <input type="text" name="contact[phone]" id="phone" class="form-control">
                      </div>
                    </div>

                    <div class="form-group">
                      <label for="name" class="control-label col-md-3">Address</label>
                      <div class="col-md-8">
                        <textarea name="contact[address]" id="address" rows="3" class="form-control"></textarea>
                      </div>
                    </div>
                    <div class="form-group">
                      <label for="group" class="control-label col-md-3">Group</label>
                      <div class="col-md-5">
                        <select name="contact[group_id]" id="group" class="form-control">
                          <option value="">Select group</option>
                          <% Group.all.each do |group| %>
                            <option value="<%= group.id %>"><%= group.name %></option>
                          <% end %>
                        </select>
                      </div>
                      <div class="col-md-3">
                        <a href="#" id="add-group-btn" class="btn btn-default btn-block">Add Group</a>
                      </div>
                    </div>
                    <div class="form-group" id="add-new-group" style="display: none;">
                      <div class="col-md-offset-3 col-md-8">
                        <div class="input-group">
                          <input type="text" name="new_group" id="new_group" class="form-control">
                          <span class="input-group-btn">
                            <a href="#" class="btn btn-default">
                              <i class="glyphicon glyphicon-ok"></i>
                            </a>
                          </span>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-4">
                    <div class="fileinput fileinput-new" data-provides="fileinput">
                      <div class="fileinput-new thumbnail" style="width: 150px; height: 150px;">
                        <img src="http://placehold.it/150x150" alt="Photo">
                      </div>
                      <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
                      <div class="text-center">
                        <span class="btn btn-default btn-file"><span class="fileinput-new">Choose Photo</span><span class="fileinput-exists">Change</span><input type="file" name="..."></span>
                        <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="panel-footer">
              <div class="row">
                <div class="col-md-8">
                  <div class="row">
                    <div class="col-md-offset-3 col-md-6">
                      <button type="submit" class="btn btn-primary">Save</button>
                      <a href="#" class="btn btn-default">Cancel</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>

      </form>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |type, message| %>
	<%= content_tag :div, message, class: "alert alert-#{type}" %>
<% end %>

app/views/layouts/_navbar.html.erb
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

	  <%= link_to"My Contact", root_path, class: "navbar-brand text-uppercase"  %>

        </div>
        <!-- /.navbar-header -->
        <div class="collapse navbar-collapse" id="navbar-collapse">
          <div class="nav navbar-right navbar-btn">
	      <%= link_to new_contact_path, class: 'btn btn-default' do  %>
		 <i class="glyphicon glyphicon-plus"> </i>
		 Add Contact
	      <% end %>
          </div>
        </div>
      </div>
    </nav>

app/views/layouts/_sidebar.html.erb
        <div class="col-md-3">
          <div class="list-group">
		<% active = params[:group_id] == nil || params[:group_id].empty? ? 'active' : '' %>
		<%= link_to contacts_path, class: "list-group-item #{active}" do %>
			All Contacts<span class="badge"><%= Contact.count %>
		<% end %>
		<% Group.all.each do |group| %>
			<% active = params[:group_id].to_i == group.id ? 'active' : '' %> 
			<%= link_to contacts_path(group_id: group.id), class: "list-group-item #{active}" do %>
				<%= group.name  %> <span class="badge"><%= group.contacts.count %></span>
			<% end %>
		<% end %>
          </div>
        </div><!-- /.col-md-3 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactManagerRails5</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- navbar -->
	<%= render 'layouts/navbar' %>
    <!-- content -->
    <div class="container">
      <div class="row">
	<%= render 'layouts/sidebar' %>
        <div class="col-md-9">
          <%= render "layouts/messages" if !flash.empty? %>
		<%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>